# Generated by Django 2.0 on 2020-04-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=200)),
                ('profile', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'page_cn',
            },
        ),
        migrations.CreateModel(
            name='PageEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=200)),
                ('profile', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'page_en',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('first_page', models.CharField(default='', max_length=200)),
                ('url_selector', models.CharField(default='', max_length=200)),
                ('title_selector', models.CharField(default='', max_length=200)),
                ('author_selector', models.CharField(default='', max_length=200)),
                ('content_selector', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
