# Generated by Django 3.0.4 on 2020-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('summary', models.TextField(default='', max_length=50000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('pub_date', models.CharField(default='', max_length=200)),
                ('source', models.CharField(default='', max_length=200)),
                ('source_url', models.CharField(default='', max_length=200)),
                ('guid', models.CharField(default='', max_length=200)),
                ('media_content', models.CharField(default='', max_length=2000)),
                ('media_text', models.TextField(default='', max_length=50000)),
                ('profile_name', models.CharField(default='', max_length=200)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('author', models.CharField(default='', max_length=1000)),
                ('content', models.TextField(default='', max_length=200)),
                ('profile', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'page_cn',
            },
        ),
        migrations.CreateModel(
            name='PageEN',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('link', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=1000)),
                ('author', models.CharField(default='', max_length=1000)),
                ('content', models.TextField(default='', max_length=200)),
                ('profile', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'page_en',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('first_page', models.CharField(default='', max_length=200)),
                ('url_selector', models.CharField(default='', max_length=200)),
                ('title_selector', models.CharField(default='', max_length=200)),
                ('author_selector', models.CharField(default='', max_length=200)),
                ('content_selector', models.CharField(default='', max_length=200)),
                ('rss_url', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
