# Generated by Django 3.0.4 on 2020-05-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200503_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', max_length=500000),
        ),
    ]
