# Generated by Django 3.0.4 on 2020-04-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title_selector', models.CharField(max_length=200)),
                ('author_selector', models.CharField(max_length=200)),
                ('content_selector', models.CharField(max_length=200)),
            ],
        ),
    ]
