# Generated by Django 3.0.4 on 2020-04-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200406_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='urls_selector',
            new_name='url_selector',
        ),
    ]
