# Generated by Django 3.0.4 on 2020-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200503_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Selector_Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(default='', max_length=200)),
                ('title_selector', models.CharField(default='', max_length=200)),
                ('author_selector', models.CharField(default='', max_length=200)),
                ('content_selector', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('summary', models.TextField(default='', max_length=500000)),
                ('description', models.TextField(default='', max_length=50000)),
                ('type', models.CharField(default='', max_length=20)),
                ('update_time', models.TimeField(auto_now=True)),
                ('content', models.TextField(default='', max_length=5000000)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', max_length=5000000),
        ),
        migrations.AddField(
            model_name='article',
            name='process_status',
            field=models.IntegerField(default=0),
        ),
    ]
