# Generated by Django 2.2 on 2020-06-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200513_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_translation',
            name='content',
            field=models.TextField(default='', max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='article_translation',
            name='description',
            field=models.TextField(default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='article_translation',
            name='summary',
            field=models.TextField(default='', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='article_translation',
            name='type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article_translation',
            name='update_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
